import msvcrt as m
def wait():
    m.getch()

def finalBossRoom():
    print("You arrive at the room. It's a red room with very sophisticated furnishings, red carpet, red drapes, and brown-red staircases on both sides, both leading to a landing.")
    wait()
    print("21: Aight, here we is... the final room. It shouldn't be too hard. Dis room's locked up in case of emergency.")
    time.sleep(6)
    print(f"{name}: Emergency?")
    time.sleep(4)
    print("21: Dere's a room at da top of that landing. We need to blow dat open too. Dere's a switch we gotta pull, it can either bring us back to dat train station you came from, or it can lead to a \"panic room\".")
    time.sleep(10)
    print(f"{name}: Well, let's get going then, what are we waiting for?")
    time.sleep(3)
    print("21: Well, da thing is...")
    time.sleep(4)
    print("21: Dis s$*%'s too quiet, dawg.")
    time.sleep(4)
    print(f"{name}: What? What do you mean, quiet? Is something going to happen?")
    time.sleep(4)
    print("21: Maybe... ")
    time.sleep(3)
    print("...")
    time.sleep(5)
    print("Out of nowhere, the right wall starts cracking.")
    time.sleep(5)
    print(f"{name}: W-what's that???")
    time.sleep(3)
    print("A huge creature breaks out of the wall, and someone's riding on top of it!")
    time.sleep(4)
    print("21: Oh no, it's her! I shoulda known that broad was gonna pop up!")
    time.sleep(4)
    print("")

finalBossRoom()